export const BAPTIS_SHOW_RESET = 'BAPTIS_SHOW_RESET'
export const BAPTIS_SHOW_SET_ERROR = 'BAPTIS_SHOW_SET_ERROR'
export const BAPTIS_SHOW_SET_RETRIEVED = 'BAPTIS_SHOW_SET_RETRIEVED'
export const BAPTIS_SHOW_TOGGLE_LOADING = 'BAPTIS_SHOW_TOGGLE_LOADING'
