export const BAPTIS_DELETE_RESET = 'BAPTIS_DELETE_RESET'
export const BAPTIS_DELETE_SET_ERROR = 'BAPTIS_DELETE_SET_ERROR'
export const BAPTIS_DELETE_SET_DELETED = 'BAPTIS_DELETE_SET_DELETED'
export const BAPTIS_DELETE_TOGGLE_LOADING = 'BAPTIS_DELETE_TOGGLE_LOADING'
